version: '3.3'

services:
  teamcity:
    image: jetbrains/teamcity-server:2020.1.5
    volumes:
      - ./data/server/datadir:/data/teamcity_server/datadir
      - ./data/server/logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent:2020.1.5
    volumes:
      - ./data/agent:/data/teamcity_agent/conf
    environment:
      SERVER_URL: http://teamcity:8111